### ISSUE TITLE
Support OpenMP copyprivate

### ISSUE THREAD

**Issue by addison-coderrect** [coderrect-inc/OpenRace#125]
Copyprivate is used to broadcast data from one thread to other threads.

For data race detection, I think we can safely ignore copyprivate as the variables affected by copyprivate must be private and cannot be part of a data race. If copyprivate can be safely ignored, the copyprivate API can be added to the list of OpenMP APIs that have no effect on race detection.

https://github.com/coderrect-inc/OpenRace/blob/9d4ff1d9bb014f2123275e8c04c9bf6cb5a319c6/src/LanguageModel/OpenMP.h#L62

Someone will need to check the specification an confirm.
See the OpenMP Specification for [copyprivate][1].

[1]: https://www.openmp.org/spec-html/5.0/openmpsu108.html#x141-6070002.19.6.2

Re: #124

**Comment by bz-liu** [comment]
All variables in `list` of `copyprivate(list)` are free of data races, because (copied from [here](https://www.openmp.org/spec-html/5.0/openmpsu108.html#x141-6070002.19.6.2)):

"2.19.6.2 copyprivate Clause
*Summary*
The copyprivate clause provides a mechanism to use a private variable to broadcast a value from the data environment of one implicit task to the data environments of the other implicit tasks that belong to the parallel region. To **avoid data races**, concurrent reads or updates of the list item must be synchronized with the update of the list item that occurs as a result of the copyprivate clause."

and 

"RestrictionsThe restrictions to the copyprivate clause are as follows:
- All list items that appear in the copyprivate clause must be either threadprivate or private in the enclosing context."

and `copyprivate` must be used together with the `omp single` directive: 

"one thread reads and initializes private vars. which are copied to other threads before they leave barrier." (refer to [here](https://www.ibm.com/docs/en/zos/2.3.0?topic=processing-pragma-omp-single) and [here](https://core.ac.uk/download/pdf/145690498.pdf) and [here](https://cims.nyu.edu/~stadler/hpc17/material/ompLec.pdf)).

So `list` are thread-safe. Added to the list of OpenMP APIs.
