### ISSUE TITLE
Crash involving HybridCtx

### ISSUE THREAD

**Issue by tanzircoderrect** [coderrect-inc/OpenRace#204]
**Describe the bug**
DRB100 and 101 fail starting from this weekend. I am suspecting the change of context from KOrigin<3> to the new HybridContext in RaceModel.h is causing the problem.

**Expected behavior**
Test cases DRB100 and 101 should pass.

**To Reproduce**
Run the current version with DRB100 and 101 in gdb to see the stack trace

**Additional context**

**Comment by bz-liu** [comment]
The problem is at `ConsGraphBuilder::processCallSite`: should use `getOrCreatePtrNode` to create new or retrieve existing pointers for formal/actual parameters, but used `getPtrNode` that can panic if no such pointer exists. 

But after the change, the assertion below fails when seeing function with name `"_Z8gen_taski"` during generating function summary for `.omp_outlined..1`.

https://github.com/coderrect-inc/OpenRace/blob/1a7d19fcaa30fe67bf7494193af1f115041d7e79/src/IR/Builder.cpp#L194

**Comment by bz-liu** [comment]
After merging with your develop branch, this assertion failure disappeared.
