### ISSUE TITLE
Support OpenMP target teams distribute

### ISSUE THREAD

**Issue by BradSwain** [coderrect-inc/OpenRace#217]
It looks like the most common way to offload OpenMP code is using target [teams][1] distribute.

See DRB cases 97, 116, 144-154, 56-157, and 160-164 for examples.

This is a sub issue of overall support for OpenMP target (#191 )

[1]: https://www.openmp.org/spec-html/5.0/openmpse15.html#x57-910002.7

**Comment by BradSwain** [comment]
For reference, I am putting my understanding of target teams distribute here.

The "target teams distribute" can be thought of as a way to run OpenMP code on a GPU.

GPUs are designed for highly parallel computation, but are more restricted in what they can do.
At a (very) high level, GPUs can be thought of as having many teams, each of which is made up of many threads.

```shell
Team 0                Team 1               ...  Team K
|-----------------|   |-----------------|       |-----------------|
|     Thread 1    |   |     Thread 1    |       |     Thread 1    |
|-----------------|   |-----------------|       |-----------------|
|     Thread 2    |   |     Thread 2    |       |     Thread 2    |
|-----------------|   |-----------------|       |-----------------|
|       ...       |   |       ...       |       |       ...       |
|-----------------|   |-----------------|       |-----------------|
|     Thread N    |   |     Thread N    |       |     Thread N    |
|-----------------|   |-----------------|       |-----------------|
```

Here is a simple example for `target teams distribute`.

```cpp
#pragma omp target teams distribute parallel for
for (int i = 0; i < 100; i++) {
  A[i] = ...
}
```

In the above example:
- `target` says we will offload this region to a new device (maybe a GPU).
- `teams` says we should split the loop across all teams on the device
- `distribute` says we should split the work given to each team among the threads on a team


For example, on a GPU with 5 teams of 20 threads the `teams` clause will split the loop such that:
 - iterations 0-19 would be assigned to team 0
 - iterations 20-39 would be assigned to team 1
 - iterations 40-59 would be assigned to team 2
 - and so on

Then these iterations would be divided amongst each team through the `distribute` clause.
For example, in team 1
 - Thread 0 would get iteration 0
 - Thread 1 would get iteration 1
 - and so on
 
 In team 2
 - Thread 0 would get iteration 20
 - Thread 1 would get iteration 21
 - and so on

Without including the `distribute` clause, thread 0 in each team would execute all of the iterations assigned to that team.

**Comment by bz-liu** [comment]
For my understanding after reading your understanding, the key problems are:

1. how many teams, how many threads in a team; 
2. how does the data/array offload to other devices, e.g., which team has been assigned which elements/indexes from array;

both of them are determined by GPU/other devices, which is unknown for static analysis. 

So, we need to model this `target` conservatively: 
Because there are mutex inside a team, there will be no races. 
It is not important to openrace whether there exist `distribute` in `omp target`, since races only exist among teams. 
Meanwhile, because we cannot know the offload detail (problem 2), we can model the code block inside the for loop (continue with the above example) as a thread in a team:

```cpp 
#pragma omp target teams distribute parallel for
for (int i = 0; i < 100; i++) {
  #pragma omp critical
  counter++;
}
```
becomes 
```cpp 
--- Thread 0 // main
fork target team 1 
fork target team 2 

--- Thread 1 // team 1
write counter

--- Thread 2 // team 2
write counter
```

Then, we check whether `counter` is shared; or for complex cases, we need an array index analysis to check whether two threads from two teams have overlapped indexes. 

**But**, can `barrier` be inserted inside `omp target teams` block? then all GPU units/teams will join and then resume?
