### ISSUE TITLE
Crash on Kripke

### ISSUE THREAD

**Issue by addison-coderrect** [coderrect-inc/OpenRace#280]
**Describe the bug**
I'm unclear to the precise cause of this crash, but [this assertion](https://github.com/coderrect-inc/OpenRace/blob/b0ec729e409c79a4b1623f61876a29baef0f10ec/src/PointerAnalysis/Models/MemoryModel/FieldSensitive/Layout/Util.cpp#L34) does not hold when OpenRace is run against Kripke.

**Expected behavior**
The crash should not occur.

**To Reproduce**
Run [this PR](https://github.com/coderrect-inc/OpenRace/pull/277) against Kripke.

**Comment by bz-liu** [comment]
The root cause (I guess) of this assertion fail is because LLVM cannot/does not further identify the type of array elements. 

The assertion fails on the following GEP IR:
```
%74 = getelementptr inbounds %"struct.std::array.149", %"struct.std::array.149"* %4, i64 0, i32 0, i64 undef
```

The assertion checks whether we correctly canoicalize GEP (`getelementptr`) instruction (in `src/PreProcessing/Passes/CanonicalizeGEPPass.cpp`). If we fully canoicalize a GEP instruction, the GEP should have 2 or 3 operands. 

Here, we have 4 (i.e., `%4`, `0`, `0`, `undef`). One main reason is LLVM cannot/does not further identify the type of "struct.std::array.149" so that we cannot further disassemble the nested instructions inside the GEP to reduce the number of operands (step 1 in `CanonicalizeGEPPass.cpp`). Another thing is `undef` (uninitialized value: https://llvm.org/docs/FAQ.html#what-is-this-undef-thing-that-shows-up-in-my-code), but our code can handle this case.

*Solution* 
Update the assertion to include such pattern and also update the comments in the function `getGEPStepSize` (it can handle this special case).
